# Problema de la mochila Pokemon

In [39]:
# importamos las librerías necesarias 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [40]:
# Modificamos los parámetros de los gráficos en matplotlib
from matplotlib.pyplot import rcParams

rcParams['figure.figsize'] = 12, 6 # el primer dígito es el ancho y el segundo el alto
rcParams["font.weight"] = "bold"
rcParams["font.size"] = 10
rcParams["axes.labelweight"] = "bold"

### Cargamos ambos datasets

In [41]:
df_pokemon = pd.read_csv("pokemon.csv", delimiter = ",", on_bad_lines='skip')
df_pokedex = pd.read_csv("pokedex.csv", delimiter = ",", on_bad_lines='skip')

In [42]:
df_pokemon

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [43]:
df_pokedex

,NUMERO,NOMRE,TIPO_1,TIPO_2,PUNTOS_DE_VIDA,PUNTOS_ATAQUE,PUNTOS_DEFENSA,PUNTOS_ATAQUE_ESPECIAL,PUNTO_DEFENSA_ESPECIAL,PUNTOS_VELOCIDAD,NOMBRE_GENERATIONS,LEGENDARIO
0,1,Bulbasaur,Planta,Veneno,45,49,49,65,65,45,1,FALSO
1,2,Ivysaur,Planta,Veneno,60,62,63,80,80,60,1,FALSO
2,3,Venusaur,Planta,Veneno,80,82,83,100,100,80,1,FALSO
3,4,Mega Venusaur,Planta,Veneno,80,100,123,122,120,80,1,FALSO
4,5,Charmander,Fuego,NaN,39,52,43,60,50,65,1,FALSO
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Roca,Hada,50,100,150,100,150,50,6,VERDADERO
796,797,Mega Diancie,Roca,Hada,50,160,110,160,110,110,6,VERDADERO
797,798,Hoopa contenido,Psiquico,Fantasma,80,110,60,150,130,70,6,VERDADERO
798,799,Hoopa desatado,Psiquico,Siniestro,80,160,60,170,130,80,6,VERDADERO
799,800,Volcanion,Fuego,Agua,80,110,120,130,90,70,6,VERDADERO

In [44]:
# Contar datos perdidio/fantantes
df_pokedex.isna().sum()
df_pokemon.isna().sum()

abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classfication          0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64

In [50]:
# La información útil sobre los datos guardados en formato dataFrame
df_pokemon.info()
df_pokedex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NUMERO                  800 non-null    int64
 1   NOMRE                   800 non-null    object
 2   TIPO_1                  800 non-null    object
 3   TIPO_2                  413 non-null    object
 4   PUNTOS_DE_VIDA          800 non-null    int64
 5   PUNTOS_ATAQUE           800 non-null    int64
 6   PUNTOS_DEFENSA          800 non-null    int64
 7   PUNTOS_ATAQUE_ESPECIAL  800 non-null    int64
 8   PUNTO_DEFENSA_ESPECIAL  800 non-null    int64
 9   PUNTOS_VELOCIDAD        800 non-null    int64
 10  NOMBRE_GENERATIONS      800 non-null    int64
 11  LEGENDARIO              800 non-null    object
dtypes: int64(8), object(4)
memory usage: 75.1+ KB